### ISSUE TITLE
Please update ffmpeg-batch

### ISSUE THREAD

**Issue by opusforlife2** [chtof/chocolatey-packages#16]
Version 2.1.4 is now available.

**Comment by chtof** [comment]
Status: **Review**
- https://chocolatey.org/packages/ffmpeg-batch/2.1.4
- https://chocolatey.org/packages/ffmpeg-batch.install/2.1.4
- https://chocolatey.org/packages/ffmpeg-batch.portable/2.1.4

**Comment by chtof** [comment]
Updated. Thank you for this information.
