### ISSUE TITLE
[Request] Voicemeter Banana & Potato packages. 

### ISSUE THREAD

**Issue by AaronNBrock** [chtof/chocolatey-packages#21]
VB-Audio offers a few different versions of voice meter: 

Regular: https://www.vb-audio.com/Voicemeeter/index.htm
Banana: https://www.vb-audio.com/Voicemeeter/banana.htm
Potato: https://www.vb-audio.com/Voicemeeter/potato.htm

It'd be great if there were packages for banana & potato as well as regular.  Thanks!

**Comment by chtof** [comment]
https://chocolatey.org/packages/voicemeeter-banana
https://chocolatey.org/packages/voicemeeter-banana.install
https://chocolatey.org/packages/voicemeeter-banana.portable
https://chocolatey.org/packages/voicemeeter-potato
https://chocolatey.org/packages/voicemeeter-potato.install
https://chocolatey.org/packages/voicemeeter-potato.portable
