### ISSUE TITLE
[Request] Evga Flow Control

### ISSUE THREAD

**Issue by vinguan** [chtof/chocolatey-packages#22]
Hello, 

I see that you are the maintenaer of some EVGA's packages on chocolatey, I have a EVGA 280mm CLC cooler from them would be great to install their [Flow Control](https://www.evga.com/software/), [latest version here](https://cdn.evga.com/utilities/EVGA_Flow_Control_Setup_v2.0.9.zip),  to manage it from chocolatey too. 

Thanks in advance.

**Comment by chtof** [comment]
Hello,

https://chocolatey.org/packages/evga-flow-control
