### ISSUE TITLE
Question: Why does fontforge require autohotkey?

### ISSUE THREAD

**Issue by FredHappyface** [chtof/chocolatey-packages#23]
Hi, cheers for providing fontforge to chocolatey. I've had quite a bit of fun playing around with it

I was wondering why the chocolatey package requires autohotkey? I've had a search around online and cannot find much on it.

Any automation that I use with ff is with python so I'm not too sure on what the purpose is?

Thanks for your time on this :)

**Comment by chtof** [comment]
Hi, to be a valid package, a package must be silently installed and uninstalled successfully.
For the uninstallation, even when using silent options, a window appears : "Do you want to remove user preferences?". Authokey allow to send "Enter" when this window appears to select the default option.

**Comment by FredHappyface** [comment]
Ah makes sense 

Thanks :)

**Comment by nedsociety** [comment]
Several other packages seem to be affected by this issue as well. I suggest that this MUST be documented in nuspec descriptions for two reasons:

1. This seems suspicious at a glance for end users.
2. This might be a good indication for environments without GUI capability (e.g., ServerCore) to not use this package.

**Comment by chtof** [comment]
I understand your point of view but this topic should be raised to the Chocolatey Teams as it concerns all packages using AutoHotkey, you can open an issue here: https://github.com/chocolatey/choco/issues

Also, directly on the Chocolatey Page of each package, there is a **Dependencies** column. For fontforge for example, you can see the "autohotkey.install" is needed to install FontForge.
