### ISSUE TITLE
Detect it Easy out of date

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chtof/chocolatey-packages#29]
Detect it Easy is out of date. Current version is 3.00, chocolatey package version 2.05.

Seems like the author's site has not been updated, while the [github releases](https://github.com/horsicq/DIE-engine/releases) have been.

**Comment by chtof** [comment]
[Version 3.0.1](https://chocolatey.org/packages/die/3.01) under review.
Thanks for the information.

**Comment by TheCakeIsNaOH** [comment]
- The "Using AU" section in the verification.txt has an old URL.
- `diel.exe` no longer exists, there is only `die.exe` and `diec.exe`
- The start shortcut is not going be updated for 64 bit users, it is still pointing at the 32 bit folder.

**Comment by chtof** [comment]
Corrected, 
[Version 3.0.1](https://chocolatey.org/packages/die/3.01) under review.

**Comment by TheCakeIsNaOH** [comment]
Upgrading from version `2.05`, it creates leaves the old files around. It has the `2.05` files in `die_win32_portable`, and it has the `3.01` files in `die_win64_portable`.

Also, uninstalling `3.05` (after upgrading from `2.05`) leaves the old start shortcut for Detect it Easy Lite.

**Comment by TheCakeIsNaOH** [comment]
Also, the `die.exe` shortcut does not work if `--forcex86` is passed on an x64 system.

**Comment by chtof** [comment]
I have no idea how I can handle that. I have just asked to stand-by the review of this version while waiting your answer.

**Comment by TheCakeIsNaOH** [comment]
See the calibre package for how to check for `--forcex86`
https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/calibre/tools/chocolateyInstall.ps1#L17

**Comment by chtof** [comment]
```
# Remove the folder from previous versions that were win32 only
if (Test-Path $win32Dir) { Remove-Item -Recurse -Path $win32Dir -ea 0 }
```
Perhaps for next version win64dir should be also removed to avoid to keep files from a previous 64bits version installed.

Corrected version has just been submitted, thanks a lot for your help! :-)

**Comment by TheCakeIsNaOH** [comment]
> Perhaps for next version win64dir should be also removed to avoid to keep files from a previous 64bits version installed.

That is probably a good idea.

>  thanks a lot for your help! :-)

You are very welcome.
