### ISSUE TITLE
`sublimemerge` package failed automated testing

### ISSUE THREAD

**Issue by jack1142** [chtof/chocolatey-packages#34]
The `sublimemerge` package has failed automated testing done by choco-bot ([link](https://gist.github.com/choco-bot/e5c649be53a713b65dc6d240ec8b8fd4)).
It seems that it got caught by a temporary network issue and the package works fine so it should be enough to just request a test re-run on the chocolatey page.

**Comment by chtof** [comment]
https://chocolatey.org/packages/sublimemerge/0.0.2049: All checks are passing
