### ISSUE TITLE
octave installation fails

### ISSUE THREAD

**Issue by adrianinsaval** [chtof/chocolatey-packages#41]
https://github.com/chtof/chocolatey-packages/blob/5bf8e45d58c1485898154ff32b9a2a75756b78fd/automatic/octave.install/tools/chocolateyinstall.ps1#L4

what is this line? why is it there? it makes installing octave in my system fail with this message:

> Attempt to get headers for https://ftpmirror.gnu.org/octave/windows/octave-6.3.0-w64-installer.exe failed.
>   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://ftpmirror.gnu.org/octave/windows/octave-6.3.0-w64-installer.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An unexpected error occurred on a send."
> Downloading octave.install 64 bit
>   from 'https://ftpmirror.gnu.org/octave/windows/octave-6.3.0-w64-installer.exe'

**Comment by adrianinsaval** [comment]
@chtof #42 was merged but the script in chocolatey was not update, can it be update so that it actually installs?

**Comment by chtof** [comment]
Updated: https://community.chocolatey.org/packages/octave.install/6.4.0.20220121#files
