### ISSUE TITLE
Old executables cluttering bin folder

### ISSUE THREAD

**Issue by opusforlife2** [chtof/chocolatey-packages#43]
My chocolatey/bin folder contains a couple of programs that leave old exes lying around even though new versions are installed: VirtualMIDISynth and ffmpeg-batch. I have half a dozen of these exes right now, and always have to delete them manually after every few updates.

Could deleting these files be automated as part of the update process?

**Comment by chtof** [comment]
Install scripts changed, will be taken into account when a new version of this packages will be relased.

**Comment by opusforlife2** [comment]
Thank you!

Does this mean I should delete old executables one last time? Or will all of them be deleted when the relevant packages are upgraded?
