### ISSUE TITLE
l10n for Hong Kong and Taiwan

### ISSUE THREAD

**Issue by BrandonKMLee** [chtof/chocolatey-packages#45]
https://github.com/rime/weasel/issues/438#issuecomment-819233652
https://github.com/rime/rime-cantonese/issues/114

**Comment by chtof** [comment]
What is your opinion regarding latest posts on https://github.com/rime/weasel/issues/438#issuecomment-819233652 ?
Do you know how we can easily fixed your request or can I close this case?

**Comment by chtof** [comment]
@BrandonKMLee 
What is your opinion regarding latest posts on https://github.com/rime/weasel/issues/438#issuecomment-819233652 ?
Do you know how we can easily fixed your request or can I close this case?

**Comment by BrandonKMLee** [comment]
It is currently stilll up-the-air, but it is not trivial in a sense unless AHK is used.

**Comment by Raymonf** [comment]
@chtof Hello! It looks like you can pass `/T` to the Weasel setup package to have it install as a Traditional Chinese IME:

https://github.com/rime/weasel/blob/8462b83b355c444e59d37bbff04d14260b825333/output/install.nsi#L166

From what I understand, it should be possible to detect the system locale and set this flag accordingly, and/or add a flag to override the system locale check?

**Comment by chtof** [comment]
Hello @Raymonf ,
https://community.chocolatey.org/packages/weasel/0.14.3.20220220 is under review.
"/T" option has been added, could you test to check if it works as expected?
`choco install wasel --params="'/T'"`

**Comment by chtof** [comment]
Hello @Raymonf ,

Feel free to re-open this case if needed. Thank you.
