### ISSUE TITLE
Add support for the Sublime Merge dev builds with `--pre`

### ISSUE THREAD

**Issue by brian6932** [chtof/chocolatey-packages#48]
The Merge package doesn't have a `--pre` option, while [ST4's package does](https://community.chocolatey.org/packages/sublimetext4/4.0.0.412000-dev), there is a [dev branch for Merge](https://www.sublimemerge.com/dev)

**Comment by chtof** [comment]
https://www.sublimemerge.com/dev : _"Sublime Merge dev builds are currently available to everyone, but in the future will be available to licensed users only."_

**Comment by brian6932** [comment]
https://www.sublimetext.com/dev so are ST dev builds @chtof, however, that doesn't stop someone from incrementing the URL and just getting the newest dev bin. As I said before:
> [ST4's package does](https://community.chocolatey.org/packages/sublimetext4/4.0.0.412000-dev)

It's not as if everyone who uses the choco package is an unlicensed user

**Comment by brian6932** [comment]
@chtof You can acquire the latest dev build here: https://www.sublimemerge.com/updates/dev_update_check
This is the same way that ST4 does it: https://github.com/jack1142/choco-auto/blob/main/automatic/sublimetext4/update.ps1
I don't mind mirroring the update.ps1 for Merge and PRing it, if you don't mind.
