### ISSUE TITLE
Locale Emulator 2.5.0.0 and 2.5.0.1 failed automated package testing and got rejected

### ISSUE THREAD

**Issue by jack1142** [chtof/chocolatey-packages#50]
https://community.chocolatey.org/packages/locale-emulator/2.5.0.0
https://community.chocolatey.org/packages/locale-emulator/2.5.0.1

**Comment by chtof** [comment]
Corrected version of locale-emulator 2.5.0.1 has just been published (under review) as locale-emulator.2.5.0.10 (technical reasons).
