### ISSUE TITLE
Eset reports WinGo/Ngrok.A security risk

### ISSUE THREAD

**Issue by cloo** [chtof/chocolatey-packages#53]
C:\laragon\bin\ngrok\ngrok.exe	
a variant of WinGo/Ngrok.A potentially unsafe application	
cleaned by deleting

**Comment by chtof** [comment]
@cloo, I raised an alert regarding this issue and it seems Eset does no longer detect anything, maybe it was a false positive corrected with Eset definition updates.
Could you check again if you notice the same behavior?

**Comment by chtof** [comment]
@cloo Have you read my previous post?

**Comment by chtof** [comment]
@cloo Feel free to re-open this case if needed. Thank you.
