### ISSUE TITLE
[voicemeeter] package source missing

### ISSUE THREAD

**Issue by flcdrg** [chtof/chocolatey-packages#54]
https://community.chocolatey.org/packages/voicemeeter points to https://github.com/chtof/chocolatey-packages/tree/master/automatic/voicemeeter, but that doesn't seem to exist.

There's also an update available at https://vb-audio.com/Voicemeeter/index.htm

**Comment by chtof** [comment]
Package source has been uploaded on https://community.chocolatey.org/packages/voicemeeter/1.0.8.2 is under review.
