### ISSUE TITLE
lossless-cut 3.42.0 broken

### ISSUE THREAD

**Issue by felix9** [chtof/chocolatey-packages#56]
lossless-cut 3.42.0 doesn't install because it fails checksum.

It looks like the maintainer updated and rebuilt 3.42.0 to fix a breakage, without changing the release tag, some hours after the auto-update of the chocolatey installer.
https://github.com/mifi/lossless-cut/commit/a380de70dddf69ebdcc128ea3b4148daaa850da8

**Comment by chtof** [comment]
Corrected, https://community.chocolatey.org/packages/lossless-cut/3.42.0.20220205
