### ISSUE TITLE
Kid3 old files left behind after update

### ISSUE THREAD

**Issue by opusforlife2** [chtof/chocolatey-packages#61]
Hey. In the `kid3 > tools` folder, there are folders from previous versions left behind, such as:

```
kid3-3.8.0-win32
kid3-3.8.1-win32
kid3-3.8.2-win32
kid3-3.8.3-win32-x64
kid3-3.8.4-win32-x64
kid3-3.8.5-win32-x64
```

and in the `kid3` folder, these old files:

```
kid3-3.8.5-win32-x64.zip.txt
kid3-3.8.6-win32-x64.zip.txt
kid3-3.8.7-win32-x64.zip.txt
```

and so on. Is it possible to ensure these are deleted when the package is upgraded? They took up half a GB of space before I noticed them.

**Comment by chtof** [comment]
Thank you for this information.
Since version 3.9.1 of the Chocolatey package, the downloaded zip file for kid3 is now deleted once uncompressed.
