### ISSUE TITLE
[issue] SALOME package can't be installed

### ISSUE THREAD

**Issue by Foadsf** [chtof/chocolatey-packages#66]
Following [this DISQUS comment](http://disq.us/p/2opzq8u), and [this Tweet](https://twitter.com/fsfarimani/status/1522239018288574464?s=20&t=K_Pw90F1smt0CkUvnHDkUw), I would appreciate it if you could fix SALOME's Chocolatey package.

**Comment by chtof** [comment]
Corrected, under review: https://community.chocolatey.org/packages/salome/9.8.0.20220508

**Comment by Foadsf** [comment]
<pre>
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 (6009) The directory is read-only: [\\?\C:\ProgramData\chocolatey\lib-bkp\salome\tools\SALOME-9.8.0\W64\EXT\lib\tcl8.6\msgs]
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 (6009) The directory is read-only: [\\?\C:\ProgramData\chocolatey\lib-bkp\salome\tools\SALOME-9.8.0\W64\EXT\lib\tcl8.6\msgs]
Maximum tries of 3 reached. Throwing error.
Attempted to remove 'C:\ProgramData\chocolatey\lib-bkp\salome' but had an error::
 (6009) The directory is read-only: [\\?\C:\ProgramData\chocolatey\lib-bkp\salome\tools\SALOME-9.8.0\W64\EXT\lib\tcl8.6\msgs]
</pre>

any idea what this error message is? 🤔
