### ISSUE TITLE
Elmer FEM Chocolatey packages are old

### ISSUE THREAD

**Issue by Foadsf** [chtof/chocolatey-packages#67]
Hi Christophe,

Sadly, the [Elmer FEM packages](https://community.chocolatey.org/packages?q=elmer) are outdated. Can you be kind to upgrade them to the latest version? You may find the latest binaries [here](http://www.nic.funet.fi/pub/sci/physics/elmer/bin/windows/). Thanks for your support in advance.

**Comment by chtof** [comment]
No new event on this issue for one year, I close this issue. Feel free to open it again if needed.
