### ISSUE TITLE
[natron] A new release version is available

### ISSUE THREAD

**Issue by jedfrechette** [chtof/chocolatey-packages#69]
A new version of Natron is available. Below is the changelog listing difference compared to the current packaged version (2.3.15).

### Known issues

- Crash when closing a project window on macOS 12+ (Qt4 only). #712
- Rendering sometimes silently stalls after X frames. #248
- Some image formats may have issues (PCX, PSB). #602
- MTS video files are sometimes not read correctly. #186

### Changes

- Added support for render progress in taskbar icon (Windows/macOS). #766
- Added palette support in color selector. #754
- Allow creating a node with the same name that was just deleted. #732
- Natron can now keep up to 32 project backups (see Preferences/General/Save versions). #562
- Only display the overlays for nodes that are in the viewer render path and have their properties panel maximized. Can be disabled in Preferences/Viewer. #744
- Fix rendering from Python (by calling app.render()) when nodes use Python expressions. #560
- Fix drawing of closed Bezier overlays. #659
- RotoPaint does not reconnect to the viewer at each stroke by default. Added a button to the viewer interface to re-enable this behavior. #641

### Changes

- Fix OpenFX overlay actions being executed in the wrong order. #711
- Fix enabling node preview from Python. #710
- Do not display the "Loading project" splashscreen on macOS 12+ to avoid crash due to Qt4 bug. #712

### Plugins

- Fix bug in Transform plugin interact. #708
- Fix EXR reader outputing the color plane only when an OCIO transform is applied. #714
- The OpenColorIO plugins can now use OpenColorIO 2.1.

### Changes

- Default number of render threads is more reasonable on multi-core systems: `min(num_cores, RAM/3.5Gb)`. #554
- Fix checkerboard drawing on macOS Catalina and later. #614
- Fix undoing "Reset to default" on parameters. #630
- Fix NodeGraph manipulation and navigation issues. #491 #627
- Fix Retina/High-DPI display issues on macOS, Windows and Linux/X11. #635
- Fix multi-dimensional parameter linking (bug introduced in 2.4.0 #594). #631
- Fix bug where any argument containing an integer between commas would be interpreted as a frame range. #644
- Python: `app.saveProject`  and `app.saveProjectAs` now do project variable substitution, as in `app.saveProjectAs("[Variable]/output.ntp")`.
- Fix ASCII curve import. #656
- New color selection dialog for RGB and RGBA knobs. #210
- Fix histogram smoothing (was 5 times too strong).
- Add Python functions `guiApp.copySelectedNodes` and `guiApp.pasteNodes`. #390 #674 #675

### Plugins

- Transform, CornerPin, Position and Ramp nodes now display the motion path.
- HueCorrect now has the ability to do hue vs. hue adjustments, with an option to change the background curve guide. #610
- Merge: Fix behavior on most operators when A is not connected or A's RoD and B's RoD are disjoint. #647
- Reformat: fix bugs when "turn" is checked with Resize Type = None or Type = Scale.
- Write: Remove file first when overwriting. #666
- Mirror: Fix crash. #660
- SeNoise: Add option for colored noise.

### Changes

- Updated documentation. #572 #566 #551 #539 #538 #537 #520 #514
- Handle console output on Windows. #524
- Detect user installed fonts on Windows 10. #523
- New Windows installer. #596
- Improvements to SequenceFileDialog. #565
- Snap timeline alpha cursor to nearest frame. #574
- Handle UTF-8 values in KnobTable (fixes use of project path containing Unicode). #578
- Tabs UI adjustments. #564
- Do not allow Python keywords as node name or scriptname. #588
- Always serialize nodes with an expression or a link, even if they have the default value. #585
- Support cloned group nodes or hard links between groups. #568 #579 #594 #598
- Default keyframe interpolation method for strokes and shapes is now "Smooth" (was "Linear"). #597
- Fix animation of Roto Beziers with non-broken tangents. #102
- Remember properties panels state when reopening project. #168
- Fix slow nodegraph display on macOS 11 Big Sur. #606

### Plugins

- ReadFFmpeg, WriteFFmpeg: upgrade to work more nicely with the FFmpeg 4 API. #148 #231 #241
- ReadFFmpeg: add support for reading AV1 & Canopus HQ/HQX/Lossless.
- WriteFFmpeg: add support for writing AV1 & Cineform HD.
- Fix another bug in DenoiseSharpen that caused crash when stoping/aborting. #300
- Fix Lin2Log to be consistent with Log2Lin. #570
- Merge: never consider RGB as being transparent by default - this is OK for unpremultiplied compositing (After Effects) but is invalid in a premultiplied compositor such as Natron or Nuke. Users still have the option to ignore the alpha channel. #571
- WriteOIIO: Do not add "Color." to the channel names of the color plane (affects mainly OpenEXR). #583
- Writers: when writing RGBA to format that does not support alpha, just drop alpha - don't premultiply. #582
- RGBtoHSL: Fix bug with white and superwhite values. #512
- Reformat: Default to project size. #533

**Comment by chtof** [comment]
Latest version 2.4.3 available:
- https://community.chocolatey.org/packages/natron
- https://community.chocolatey.org/packages/natron.install
- https://community.chocolatey.org/packages/natron.portable
