### ISSUE TITLE
fontforge upgrade asks for confirmation

### ISSUE THREAD

**Issue by fraenki** [chtof/chocolatey-packages#8]
When upgrading fontforge from 2016.10.04 to 2019.08.01 it does not perform a silent/unattended upgrade, but instead a popup window is shown asking to uninstall the old version of fontforge.

It looks like a parameter is missing for silent/unattended upgrades.

**Comment by chtof** [comment]
After a few tests, this behavior appears only from an update from an old version. The Chocolatey package has been updated to version 2019.08.01 a while ago so I think the install script shouldn't be changed if you agree.

**Comment by fraenki** [comment]
@chtof So, just to ensure that I understand you correctly: This issue only affects updates from older versions, i.e. from 2016.10.04 to 2019.08.01. But updates from 2019.08.01 to any future version are not affected. Is this assumption correct?

**Comment by chtof** [comment]
Yes, tried after having manually installed 2019.04.13 version and installed 2019.08.01 version.

**Comment by fraenki** [comment]
@chtof Thanks.
