### ISSUE TITLE
[davmail] Missing Java dependency

### ISSUE THREAD

**Issue by C-Duv** [chtof/chocolatey-packages#81]
The [DavMail Gateway](https://davmail.sourceforge.net) needs Java to run but the `davmail` Chocolatey package's `.nuspec` file does not specify `javaruntime` as a dependency.

Manuelly installing Java (via the `javaruntime` or other) allows DavMail to run.

I think the dependency should be explicitly declared in the `.nuspec` file.

I tried open a PR but I've experienced issues with architecture version selection for Java (32 or 64 bits): the `davmail` package installs 64 bits where it can but can't find a Chocolatey package for 64 bits Java.

**Comment by chtof** [comment]
Thank you for this information, the description of the Chocolatey package has just been updated to display this prerequisites:
https://community.chocolatey.org/packages/davmail/6.1.0.342300#description

```
 ## Prerequisites
Davmail needs Java to be launched so you have to install the Java runtime of your choice if Java is not installed on your machine.
```
