### ISSUE TITLE
Add binary shim for Sublime Merge's smerge CLI command

### ISSUE THREAD

**Issue by Jackenmen** [chtof/chocolatey-packages#83]
Currently after installing Sublime Merge, `smerge` cannot be ran from the terminal as it's not part of the PATH. I would like to suggest that the install script adds a shim for `smerge` so that it can be run from the terminal without having to manually alter the path. This can be done using a shimming feature that Chocolatey provides - it allows you to put an application's CLI binaries on the PATH without cluttering the PATH environment variable:
https://docs.chocolatey.org/en-us/features/shim

A similar change has recently been made to the `sublimetext4` package after it was requested and contributed by one of its users:
https://github.com/Jackenmen/choco-auto/commit/ae49b3253becfa252f63fa00a89b7a8b8eb53125

**Comment by chtof** [comment]
Thank your for this request, the chocolatey package has just been updated to include a binary shim for smerge: https://community.chocolatey.org/packages/sublimemerge/0.0.2085.20230518-dev#files
