### ISSUE TITLE
[outdated] Briss

### ISSUE THREAD

**Issue by teknowledgist** [chtof/chocolatey-packages#86]
Hi.  Briss is still in alpha (which isn't noted for the package), but alpha-4 was released last month with a number of fixes.  It would be good to move the dependency to an open Java too.  

I'm willing to co-maintain if you would like.

**Comment by chtof** [comment]
Hi @teknowledgist,

Thank your for this information.
The Chocolatey package has been updated for the version alpha-5.
I have also added a prerequisites in the description of the Chocolatey package regarding Java runtime and you are added of the list of the maintainers of this package.
