### ISSUE TITLE
poppler 23.03 has been out for a few weeks, can you please update the build?

### ISSUE THREAD

**Issue by jpluimers** [chtof/chocolatey-packages#88]
Hi,

According to https://poppler.freedesktop.org/releases.html the current Chocolatey based version 0.89 is almost 3 years old:

> ## Poppler 0.89 Releases
> [`poppler-0.89.0.tar.xz`](https://poppler.freedesktop.org/poppler-0.89.0.tar.xz)` (Wed May 27, 2020):`
> ` `
> ` `
> `        core:`
> `         * Add support for ResetForm action. Issue #225`
> `         * Fix crash in PDFDoc::getSignatureFields when there's no Forms at all`
> `         * Fix exporting to PS of some files with CID fonts`
> `         * Use ICC profiles in PS output (if new enough lcms is used)`
> `         * Allow almost-singular tiling pattern matrices. Issue #894`
> `         * Fix memory leak when failing to load some fonts`
> `         * CairoOutputDev: Use stroke opacity when clipping to a stroke path`
> `         * CairoOutputDev: Fix tiling patterns when pattern cell is too far. Issue #190`
> ` `
> `        glib:`
> `         * Add poppler_movie_get_aspect`
> ` `
> `        cpp:`
> `         * Add the font infos to the text_box object`

It indicates that version 23.03 has has been released early March 2023:

> ## Poppler 23.03 Releases
> [`poppler-23.03.0.tar.xz`](https://poppler.freedesktop.org/poppler-23.03.0.tar.xz)` (Wed Mar 1, 2023):`
> ` `
> ` `
> `Release 23.03.0:`
> `        core:`
> `         * PngWriter: Fix potential uninitialized memory use`

Can you please update the build to a more recent poppler version?

Current poppler Windows builds can be obtained from https://github.com/oschwartz10612/poppler-windows/releases which is at version 23.01.0-0 with version 23.03.0 pending in a pull-request: https://github.com/oschwartz10612/poppler-windows/pull/48

Regards,

--jeroen

**Comment by chtof** [comment]
Hello @jpluimers ,
Thank you for this information.
https://community.chocolatey.org/packages/poppler/22.11.0 is currently under review.

**Comment by jpluimers** [comment]
That version does not install the executables. See also https://github.com/chtof/chocolatey-packages/issues/75
